### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by serverhorror** [bdwyertech/journald-cloudwatch-logs#45]
Hi,

Would you mind adding a license?

Preferrably a permissive license like BSD or MIT, but without a license I can't even look at it (thanks, enterprise lawyers ...)

Thank you

**Comment by bdwyertech** [comment]
Sure, wanna make a PR?  I had someone else request this for another project too.  I think we went with MIT.

Curious who you work for, would love to know what kind of orgs are really tracking this sort of thing.  Mine does when they want to and then sometimes has no clue 🙃

**Comment by serverhorror** [comment]
PR created.

I work in a regulated industry (health care).

We try to pay attention. Truth be told, it's not just because we have people caring about that topic, it is also because there are certain risks attached to abusing someone elses work. We are lucky enough that the legal departement listens and now we have the backing of them so we are able to point out license abuse.

Still working on the possibility to give back more, but we'll get there :)

**Comment by bdwyertech** [comment]
Nice!  OK thanks for explanation, was curious more than anything else.  I'll merge now.  Thanks.
